require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CadencePurposesController do

  # This should return the minimal set of attributes required to create a valid
  # CadencePurpose. As you add validations to CadencePurpose, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CadencePurposesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cadence_purposes as @cadence_purposes" do
      cadence_purpose = CadencePurpose.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cadence_purposes).should eq([cadence_purpose])
    end
  end

  describe "GET show" do
    it "assigns the requested cadence_purpose as @cadence_purpose" do
      cadence_purpose = CadencePurpose.create! valid_attributes
      get :show, {:id => cadence_purpose.to_param}, valid_session
      assigns(:cadence_purpose).should eq(cadence_purpose)
    end
  end

  describe "GET new" do
    it "assigns a new cadence_purpose as @cadence_purpose" do
      get :new, {}, valid_session
      assigns(:cadence_purpose).should be_a_new(CadencePurpose)
    end
  end

  describe "GET edit" do
    it "assigns the requested cadence_purpose as @cadence_purpose" do
      cadence_purpose = CadencePurpose.create! valid_attributes
      get :edit, {:id => cadence_purpose.to_param}, valid_session
      assigns(:cadence_purpose).should eq(cadence_purpose)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CadencePurpose" do
        expect {
          post :create, {:cadence_purpose => valid_attributes}, valid_session
        }.to change(CadencePurpose, :count).by(1)
      end

      it "assigns a newly created cadence_purpose as @cadence_purpose" do
        post :create, {:cadence_purpose => valid_attributes}, valid_session
        assigns(:cadence_purpose).should be_a(CadencePurpose)
        assigns(:cadence_purpose).should be_persisted
      end

      it "redirects to the created cadence_purpose" do
        post :create, {:cadence_purpose => valid_attributes}, valid_session
        response.should redirect_to(CadencePurpose.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cadence_purpose as @cadence_purpose" do
        # Trigger the behavior that occurs when invalid params are submitted
        CadencePurpose.any_instance.stub(:save).and_return(false)
        post :create, {:cadence_purpose => { "name" => "invalid value" }}, valid_session
        assigns(:cadence_purpose).should be_a_new(CadencePurpose)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CadencePurpose.any_instance.stub(:save).and_return(false)
        post :create, {:cadence_purpose => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cadence_purpose" do
        cadence_purpose = CadencePurpose.create! valid_attributes
        # Assuming there are no other cadence_purposes in the database, this
        # specifies that the CadencePurpose created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CadencePurpose.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => cadence_purpose.to_param, :cadence_purpose => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested cadence_purpose as @cadence_purpose" do
        cadence_purpose = CadencePurpose.create! valid_attributes
        put :update, {:id => cadence_purpose.to_param, :cadence_purpose => valid_attributes}, valid_session
        assigns(:cadence_purpose).should eq(cadence_purpose)
      end

      it "redirects to the cadence_purpose" do
        cadence_purpose = CadencePurpose.create! valid_attributes
        put :update, {:id => cadence_purpose.to_param, :cadence_purpose => valid_attributes}, valid_session
        response.should redirect_to(cadence_purpose)
      end
    end

    describe "with invalid params" do
      it "assigns the cadence_purpose as @cadence_purpose" do
        cadence_purpose = CadencePurpose.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CadencePurpose.any_instance.stub(:save).and_return(false)
        put :update, {:id => cadence_purpose.to_param, :cadence_purpose => { "name" => "invalid value" }}, valid_session
        assigns(:cadence_purpose).should eq(cadence_purpose)
      end

      it "re-renders the 'edit' template" do
        cadence_purpose = CadencePurpose.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CadencePurpose.any_instance.stub(:save).and_return(false)
        put :update, {:id => cadence_purpose.to_param, :cadence_purpose => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cadence_purpose" do
      cadence_purpose = CadencePurpose.create! valid_attributes
      expect {
        delete :destroy, {:id => cadence_purpose.to_param}, valid_session
      }.to change(CadencePurpose, :count).by(-1)
    end

    it "redirects to the cadence_purposes list" do
      cadence_purpose = CadencePurpose.create! valid_attributes
      delete :destroy, {:id => cadence_purpose.to_param}, valid_session
      response.should redirect_to(cadence_purposes_url)
    end
  end

end
