require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PdksController do

  # This should return the minimal set of attributes required to create a valid
  # Pdk. As you add validations to Pdk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PdksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pdks as @pdks" do
      pdk = Pdk.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pdks).should eq([pdk])
    end
  end

  describe "GET show" do
    it "assigns the requested pdk as @pdk" do
      pdk = Pdk.create! valid_attributes
      get :show, {:id => pdk.to_param}, valid_session
      assigns(:pdk).should eq(pdk)
    end
  end

  describe "GET new" do
    it "assigns a new pdk as @pdk" do
      get :new, {}, valid_session
      assigns(:pdk).should be_a_new(Pdk)
    end
  end

  describe "GET edit" do
    it "assigns the requested pdk as @pdk" do
      pdk = Pdk.create! valid_attributes
      get :edit, {:id => pdk.to_param}, valid_session
      assigns(:pdk).should eq(pdk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pdk" do
        expect {
          post :create, {:pdk => valid_attributes}, valid_session
        }.to change(Pdk, :count).by(1)
      end

      it "assigns a newly created pdk as @pdk" do
        post :create, {:pdk => valid_attributes}, valid_session
        assigns(:pdk).should be_a(Pdk)
        assigns(:pdk).should be_persisted
      end

      it "redirects to the created pdk" do
        post :create, {:pdk => valid_attributes}, valid_session
        response.should redirect_to(Pdk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pdk as @pdk" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pdk.any_instance.stub(:save).and_return(false)
        post :create, {:pdk => { "name" => "invalid value" }}, valid_session
        assigns(:pdk).should be_a_new(Pdk)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pdk.any_instance.stub(:save).and_return(false)
        post :create, {:pdk => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pdk" do
        pdk = Pdk.create! valid_attributes
        # Assuming there are no other pdks in the database, this
        # specifies that the Pdk created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pdk.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => pdk.to_param, :pdk => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested pdk as @pdk" do
        pdk = Pdk.create! valid_attributes
        put :update, {:id => pdk.to_param, :pdk => valid_attributes}, valid_session
        assigns(:pdk).should eq(pdk)
      end

      it "redirects to the pdk" do
        pdk = Pdk.create! valid_attributes
        put :update, {:id => pdk.to_param, :pdk => valid_attributes}, valid_session
        response.should redirect_to(pdk)
      end
    end

    describe "with invalid params" do
      it "assigns the pdk as @pdk" do
        pdk = Pdk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pdk.any_instance.stub(:save).and_return(false)
        put :update, {:id => pdk.to_param, :pdk => { "name" => "invalid value" }}, valid_session
        assigns(:pdk).should eq(pdk)
      end

      it "re-renders the 'edit' template" do
        pdk = Pdk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pdk.any_instance.stub(:save).and_return(false)
        put :update, {:id => pdk.to_param, :pdk => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pdk" do
      pdk = Pdk.create! valid_attributes
      expect {
        delete :destroy, {:id => pdk.to_param}, valid_session
      }.to change(Pdk, :count).by(-1)
    end

    it "redirects to the pdks list" do
      pdk = Pdk.create! valid_attributes
      delete :destroy, {:id => pdk.to_param}, valid_session
      response.should redirect_to(pdks_url)
    end
  end

end
