require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StipplesController do

  # This should return the minimal set of attributes required to create a valid
  # Stipple. As you add validations to Stipple, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StipplesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stipples as @stipples" do
      stipple = Stipple.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stipples).should eq([stipple])
    end
  end

  describe "GET show" do
    it "assigns the requested stipple as @stipple" do
      stipple = Stipple.create! valid_attributes
      get :show, {:id => stipple.to_param}, valid_session
      assigns(:stipple).should eq(stipple)
    end
  end

  describe "GET new" do
    it "assigns a new stipple as @stipple" do
      get :new, {}, valid_session
      assigns(:stipple).should be_a_new(Stipple)
    end
  end

  describe "GET edit" do
    it "assigns the requested stipple as @stipple" do
      stipple = Stipple.create! valid_attributes
      get :edit, {:id => stipple.to_param}, valid_session
      assigns(:stipple).should eq(stipple)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stipple" do
        expect {
          post :create, {:stipple => valid_attributes}, valid_session
        }.to change(Stipple, :count).by(1)
      end

      it "assigns a newly created stipple as @stipple" do
        post :create, {:stipple => valid_attributes}, valid_session
        assigns(:stipple).should be_a(Stipple)
        assigns(:stipple).should be_persisted
      end

      it "redirects to the created stipple" do
        post :create, {:stipple => valid_attributes}, valid_session
        response.should redirect_to(Stipple.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stipple as @stipple" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stipple.any_instance.stub(:save).and_return(false)
        post :create, {:stipple => { "name" => "invalid value" }}, valid_session
        assigns(:stipple).should be_a_new(Stipple)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stipple.any_instance.stub(:save).and_return(false)
        post :create, {:stipple => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stipple" do
        stipple = Stipple.create! valid_attributes
        # Assuming there are no other stipples in the database, this
        # specifies that the Stipple created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stipple.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => stipple.to_param, :stipple => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested stipple as @stipple" do
        stipple = Stipple.create! valid_attributes
        put :update, {:id => stipple.to_param, :stipple => valid_attributes}, valid_session
        assigns(:stipple).should eq(stipple)
      end

      it "redirects to the stipple" do
        stipple = Stipple.create! valid_attributes
        put :update, {:id => stipple.to_param, :stipple => valid_attributes}, valid_session
        response.should redirect_to(stipple)
      end
    end

    describe "with invalid params" do
      it "assigns the stipple as @stipple" do
        stipple = Stipple.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stipple.any_instance.stub(:save).and_return(false)
        put :update, {:id => stipple.to_param, :stipple => { "name" => "invalid value" }}, valid_session
        assigns(:stipple).should eq(stipple)
      end

      it "re-renders the 'edit' template" do
        stipple = Stipple.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stipple.any_instance.stub(:save).and_return(false)
        put :update, {:id => stipple.to_param, :stipple => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stipple" do
      stipple = Stipple.create! valid_attributes
      expect {
        delete :destroy, {:id => stipple.to_param}, valid_session
      }.to change(Stipple, :count).by(-1)
    end

    it "redirects to the stipples list" do
      stipple = Stipple.create! valid_attributes
      delete :destroy, {:id => stipple.to_param}, valid_session
      response.should redirect_to(stipples_url)
    end
  end

end
